require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EstimatesController do

  # This should return the minimal set of attributes required to create a valid
  # Estimate. As you add validations to Estimate, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EstimatesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all estimates as @estimates" do
      estimate = Estimate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:estimates).should eq([estimate])
    end
  end

  describe "GET show" do
    it "assigns the requested estimate as @estimate" do
      estimate = Estimate.create! valid_attributes
      get :show, {:id => estimate.to_param}, valid_session
      assigns(:estimate).should eq(estimate)
    end
  end

  describe "GET new" do
    it "assigns a new estimate as @estimate" do
      get :new, {}, valid_session
      assigns(:estimate).should be_a_new(Estimate)
    end
  end

  describe "GET edit" do
    it "assigns the requested estimate as @estimate" do
      estimate = Estimate.create! valid_attributes
      get :edit, {:id => estimate.to_param}, valid_session
      assigns(:estimate).should eq(estimate)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Estimate" do
        expect {
          post :create, {:estimate => valid_attributes}, valid_session
        }.to change(Estimate, :count).by(1)
      end

      it "assigns a newly created estimate as @estimate" do
        post :create, {:estimate => valid_attributes}, valid_session
        assigns(:estimate).should be_a(Estimate)
        assigns(:estimate).should be_persisted
      end

      it "redirects to the created estimate" do
        post :create, {:estimate => valid_attributes}, valid_session
        response.should redirect_to(Estimate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved estimate as @estimate" do
        # Trigger the behavior that occurs when invalid params are submitted
        Estimate.any_instance.stub(:save).and_return(false)
        post :create, {:estimate => {}}, valid_session
        assigns(:estimate).should be_a_new(Estimate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Estimate.any_instance.stub(:save).and_return(false)
        post :create, {:estimate => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested estimate" do
        estimate = Estimate.create! valid_attributes
        # Assuming there are no other estimates in the database, this
        # specifies that the Estimate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Estimate.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => estimate.to_param, :estimate => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested estimate as @estimate" do
        estimate = Estimate.create! valid_attributes
        put :update, {:id => estimate.to_param, :estimate => valid_attributes}, valid_session
        assigns(:estimate).should eq(estimate)
      end

      it "redirects to the estimate" do
        estimate = Estimate.create! valid_attributes
        put :update, {:id => estimate.to_param, :estimate => valid_attributes}, valid_session
        response.should redirect_to(estimate)
      end
    end

    describe "with invalid params" do
      it "assigns the estimate as @estimate" do
        estimate = Estimate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Estimate.any_instance.stub(:save).and_return(false)
        put :update, {:id => estimate.to_param, :estimate => {}}, valid_session
        assigns(:estimate).should eq(estimate)
      end

      it "re-renders the 'edit' template" do
        estimate = Estimate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Estimate.any_instance.stub(:save).and_return(false)
        put :update, {:id => estimate.to_param, :estimate => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested estimate" do
      estimate = Estimate.create! valid_attributes
      expect {
        delete :destroy, {:id => estimate.to_param}, valid_session
      }.to change(Estimate, :count).by(-1)
    end

    it "redirects to the estimates list" do
      estimate = Estimate.create! valid_attributes
      delete :destroy, {:id => estimate.to_param}, valid_session
      response.should redirect_to(estimates_url)
    end
  end

end
